package com.fcant.dao;

import com.fcant.bean.Acl;
import com.fcant.bean.AclExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AclMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acl
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    long countByExample(AclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acl
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    int deleteByExample(AclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acl
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer acid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acl
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    int insert(Acl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acl
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    int insertSelective(Acl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acl
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    List<Acl> selectByExample(AclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acl
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    Acl selectByPrimaryKey(Integer acid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acl
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Acl record, @Param("example") AclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acl
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Acl record, @Param("example") AclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acl
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Acl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_acl
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    int updateByPrimaryKey(Acl record);
}