package com.fcant.dao;

import com.fcant.bean.Module;
import com.fcant.bean.ModuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    long countByExample(ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    int deleteByExample(ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer moduleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    int insert(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    int insertSelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    List<Module> selectByExample(ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    Module selectByPrimaryKey(Integer moduleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Module record, @Param("example") ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Module record, @Param("example") ModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_module
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    int updateByPrimaryKey(Module record);
}