package com.fcant.bean;

public class Acl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acl.acid
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    private Integer acid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acl.moduleid
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    private Integer moduleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acl.etype
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    private Integer etype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acl.eid
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_acl.privstatus
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    private Integer privstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acl.acid
     *
     * @return the value of t_acl.acid
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public Integer getAcid() {
        return acid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acl.acid
     *
     * @param acid the value for t_acl.acid
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public void setAcid(Integer acid) {
        this.acid = acid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acl.moduleid
     *
     * @return the value of t_acl.moduleid
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public Integer getModuleid() {
        return moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acl.moduleid
     *
     * @param moduleid the value for t_acl.moduleid
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public void setModuleid(Integer moduleid) {
        this.moduleid = moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acl.etype
     *
     * @return the value of t_acl.etype
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public Integer getEtype() {
        return etype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acl.etype
     *
     * @param etype the value for t_acl.etype
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public void setEtype(Integer etype) {
        this.etype = etype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acl.eid
     *
     * @return the value of t_acl.eid
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acl.eid
     *
     * @param eid the value for t_acl.eid
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_acl.privstatus
     *
     * @return the value of t_acl.privstatus
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public Integer getPrivstatus() {
        return privstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_acl.privstatus
     *
     * @param privstatus the value for t_acl.privstatus
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public void setPrivstatus(Integer privstatus) {
        this.privstatus = privstatus;
    }
}