package com.fcant.bean;

public class Module {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.moduleid
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    private Integer moduleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.mname
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    private String mname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.parentid
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    private Integer parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.url
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.haschildren
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    private Integer haschildren;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.mstatus
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    private Integer mstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.mlevel
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    private Integer mlevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.moduleid
     *
     * @return the value of t_module.moduleid
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public Integer getModuleid() {
        return moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.moduleid
     *
     * @param moduleid the value for t_module.moduleid
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public void setModuleid(Integer moduleid) {
        this.moduleid = moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.mname
     *
     * @return the value of t_module.mname
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public String getMname() {
        return mname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.mname
     *
     * @param mname the value for t_module.mname
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public void setMname(String mname) {
        this.mname = mname == null ? null : mname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.parentid
     *
     * @return the value of t_module.parentid
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.parentid
     *
     * @param parentid the value for t_module.parentid
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.url
     *
     * @return the value of t_module.url
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.url
     *
     * @param url the value for t_module.url
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.haschildren
     *
     * @return the value of t_module.haschildren
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public Integer getHaschildren() {
        return haschildren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.haschildren
     *
     * @param haschildren the value for t_module.haschildren
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public void setHaschildren(Integer haschildren) {
        this.haschildren = haschildren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.mstatus
     *
     * @return the value of t_module.mstatus
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public Integer getMstatus() {
        return mstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.mstatus
     *
     * @param mstatus the value for t_module.mstatus
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public void setMstatus(Integer mstatus) {
        this.mstatus = mstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.mlevel
     *
     * @return the value of t_module.mlevel
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public Integer getMlevel() {
        return mlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.mlevel
     *
     * @param mlevel the value for t_module.mlevel
     *
     * @mbg.generated Sun Jun 16 00:27:04 GMT+08:00 2019
     */
    public void setMlevel(Integer mlevel) {
        this.mlevel = mlevel;
    }
}